### ISSUE TITLE
Issue when running gulp ngrok-serve

### ISSUE THREAD

**Issue by arjunumenon** [pnp/generator-teams#225]
**Describe the bug**
Issue when running `gulp ngrok-serve` for **Tab** generator of Yo Teams. 
Once the generator has provisioned the files, when we execute `gulp ngrok-serve` we are getting the following error.

```
[12:16:36] Found additional Yo Teams plugin: yoteams-deploy
[12:16:36] Using gulpfile C:\Arjun\Codes\test-provisioning\tabs-dev-1.9\gulpfile.js
[12:16:36] Starting 'ngrok-serve'...
[12:16:36] Starting 'start-ngrok'...
[12:16:36] [NGROK] starting ngrok...
(node:10204) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at C:\Arjun\Codes\test-provisioning\tabs-dev-1.9\node_modules\yoteams-build-core\dist\ngrokTasks.js:33:62
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

1. Generate the teams app template using yo teams
2. Give the selection as **Tab**
3. After the generation is complete, execute `gulp ngrok-serve`
4. Getting the below error like mentioned above
5. We are getting the same error for version 1.8, 1.9 and 1.10

**Expected behavior**
Expected to run the ngrok and able to access the local web of the app. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10369964/121137302-23e5c180-c854-11eb-80dc-020d596bcb52.png)

**Detailed information**
 - Generator version (`generator-teams`): 3.2.0
 - Build tools version (`yoteams-build-core`): 1.2.0
 - OS: Windows 10
 - Node version: 14.0.0
 - Npm version: 6.14.1

**Additional information**

`gulp ngrok-serve` is working as expected for bot related development. We are facing issue only for the Tabs related generators.

**Comment by wictorwilen** [comment]
Thanks for reporting. I'm unable to reproduce this on both Windows and Ubuntu with different versions of node. Have you done any changes to any files (specifically the `.env`)? Can you please run the following the commands and report back the results

`node_modules\.bin\ngrok version`

and 

`find "ngrok" package-lock.json`

**Comment by arjunumenon** [comment]
Thanks wictor for the super quick response 👍

> Have you done any changes to any files (specifically the .env)?

Not exactly. I have not done anything for the env file for the TAB generator. For the bot, I had done and had updated the Appid and secret. But for TAB, I did not do any update.

> Can you please run the following the commands and report back the results
> 
> `node_modules\.bin\ngrok version`

2.3.4
![image](https://user-images.githubusercontent.com/10369964/121300109-0415d280-c914-11eb-94b4-6fd4ad3f2a25.png)

> and
> 
> find "ngrok" package-lock.json

Please find the ngrok version in the package-lock.json below.
![image](https://user-images.githubusercontent.com/10369964/121300253-37586180-c914-11eb-853a-c7240c7faf57.png)

Let me know if you need any other information from my end.

**Comment by wictorwilen** [comment]
Great, all the versions looks ok. 

It looks like ngrok is throwing an error and while handling that error in the ngrok task an other error is thrown, so we can't see the original error. 

As I can't replicate I would like you to make a small change in the JavaScript file for the ngrok gulp task. You can find the file in `node_modules\yoteams-build-core\dist\ngrokTasks.js`. In that file please comment out line 33 where the error is logged, as shown below:
![image](https://user-images.githubusercontent.com/5854279/121302863-9d37ef80-c8fa-11eb-8789-b80964170806.png)

After this run the gulp task again and report back, while I'll work on prohibiting the issue from happening in future versions.

**Comment by arjunumenon** [comment]
Thanks wictor. Good that there is no version difference with the one where you are testing. Totally appreciate you spending time on the same.

After commenting out the line, I see that the rest of the gulp tasks (except ngrok tasks) are running without any issue. 
_Updated ngroktask file below_
![image](https://user-images.githubusercontent.com/10369964/121305988-ea788900-c91b-11eb-9be2-58e28c4f8539.png)


Following is the result I am getting.
![image](https://user-images.githubusercontent.com/10369964/121305196-f152cc00-c91a-11eb-9757-c2157f79c4fb.png)

![image](https://user-images.githubusercontent.com/10369964/121305267-07608c80-c91b-11eb-958d-1e6d6e7d4a0c.png)

As you can see somehow ngrok tunneling is not happening and due to that ngrok URLs are not getting generated.

**Comment by wictorwilen** [comment]
Thanks! Let's try another thing, let's explicitly log the error in another way. Try changing the same line to: 

``` TypeScript
 fancy_log_1.default.error(err);
```

**Comment by arjunumenon** [comment]
That worked as expected 👍

Now we have a detailed error response from ngrok.default.connect call. Adding the details below.

```
gulp ngrok-serve
[15:56:29] Found additional Yo Teams plugin: yoteams-deploy
[15:56:29] Using gulpfile C:\Arjun\Codes\test-tabs-gen\tabs-1.9\gulpfile.js
[15:56:29] Starting 'ngrok-serve'...
[15:56:29] Starting 'start-ngrok'...
[15:56:29] [NGROK] starting ngrok...
[15:56:29] NgrokClientError
    at NgrokClient.request (C:\Arjun\Codes\test-tabs-gen\tabs-1.9\node_modules\ngrok\src\client.js:39:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async connectRetry (C:\Arjun\Codes\test-tabs-gen\tabs-1.9\node_modules\ngrok\index.js:29:22) {
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: true,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      errored: false,
      closed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: [StringDecoder],
      encoding: 'utf8',
      [Symbol(kPaused)]: null
    },
    _events: [Object: null prototype] {
      end: [Array],
      error: [Array],
      aborted: [Array],
      readable: [Array],
      finish: [Function: onfinish],
      close: [Function: onclose]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      _peername: [Object],
      [Symbol(asyncId)]: 70,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'content-type': 'application/json',
      date: 'Wed, 09 Jun 2021 10:26:29 GMT',
      'content-length': '168',
      connection: 'close'
    },
    rawHeaders: [
      'Content-Type',
      'application/json',
      'Date',
      'Wed, 09 Jun 2021 10:26:29 GMT',
      'Content-Length',
      '168',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: 'http://127.0.0.1:4040/api/tunnels',
    method: null,
    statusCode: 503,
    statusMessage: 'Service Unavailable',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      _peername: [Object],
      [Symbol(asyncId)]: 70,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _consuming: true,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 10,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /api/tunnels HTTP/1.1\r\n' +
        'user-agent: got (https://github.com/sindresorhus/got)\r\n' +
        'content-type: application/json\r\n' +
        'accept: application/json\r\n' +
        'content-length: 118\r\n' +
        'accept-encoding: gzip, deflate, br\r\n' +
        'Host: 127.0.0.1:4040\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/tunnels',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      timings: [Object],
      emit: [Function (anonymous)],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(reentry)]: true
    },
    timings: {
      start: 1623234389731,
      socket: 1623234389731,
      lookup: 1623234389731,
      connect: 1623234389731,
      secureConnect: undefined,
      upload: 1623234389731,
      response: 1623234389731,
      end: 1623234389731,
      error: undefined,
      abort: undefined,
      phases: [Object]
    },
    emit: [Function (anonymous)],
    requestUrl: 'http://127.0.0.1:4040/api/tunnels',
    redirectUrls: [],
    request: Request {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 16,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      requestInitialized: true,
      redirects: [],
      retryCount: 0,
      _progressCallbacks: [],
      write: [Function: onLockedWrite],
      end: [Function: onLockedWrite],
      options: [Object],
      requestUrl: 'http://127.0.0.1:4040/api/tunnels',
      _cannotHaveBody: false,
      _noPipe: true,
      [Symbol(kCapture)]: false,
      [Symbol(downloadedSize)]: 168,
      [Symbol(uploadedSize)]: 118,
      [Symbol(serverResponsesPiped)]: Set(0) {},
      [Symbol(stopReading)]: true,
      [Symbol(triggerRead)]: false,
      [Symbol(jobs)]: [],
      [Symbol(body)]: '{"subdomain":"","region":"","addr":"3007","authtoken":"","proto":"http","name":"5cffca7b-bd7d-4613-8a63-250338358a62"}',
      [Symbol(bodySize)]: 118,
      [Symbol(cancelTimeouts)]: [Function: cancelTimeouts],
      [Symbol(unproxyEvents)]: [Function (anonymous)],
      [Symbol(request)]: [ClientRequest],
      [Symbol(originalResponse)]: [Circular *1],
      [Symbol(isFromCache)]: false,
      [Symbol(responseSize)]: 168,
      [Symbol(response)]: [Circular *1],
      [Symbol(startedReading)]: true
    },
    isFromCache: false,
    ip: '127.0.0.1',
    retryCount: 0,
    rawBody: <Buffer >,
    body: '',
    [Symbol(kCapture)]: false
  },
  body: ''
}
[15:56:29] Finished 'start-ngrok' after 261 ms
[15:56:29] Starting 'serve'...
[15:56:29] Starting 'nuke'...
[15:56:29] Finished 'nuke' after 12 ms
[15:56:29] Starting 'build'...
[15:56:29] Starting 'webpack'...
[15:56:29] Starting 'webpack:client'...
[15:56:29] Starting 'webpack:server'...
[15:57:00] Finished 'webpack:server' after 31 s
```

**Comment by wictorwilen** [comment]
Ok, seems like your machine cannot establish the connection to the ngrok services. 

Let's try to start ngrok manually by running: `./node_modules/.bin/ngrok http 80` 

Are you behind any firewall or proxies? It's fairly common these days that ngrok is blocked by companies.

**Comment by arjunumenon** [comment]
Thanks for the guidance on that. I don't think ngrok service is NOT getting blocked on the dev machine. 

Just to give more information on that same - I am using an independent Azure VM instance which is not part of any corporate firewall. That was the reason why I had spinned-up a new VM on Azure
In this situation as a work-around, I am relying on the work-around where I am manually initiating ngrok and using that URL on the configuration so that I can test the tab in the Teams interface.

gulp ngrok-serve is a real boon which will avoid me to use that multiple steps 🙂. 

I had tried executing ngrok from `./node_modules/.bin/ngrok http 80` and the service is getting tunneled without any issue. 

![image](https://user-images.githubusercontent.com/10369964/121369981-f125f100-c959-11eb-8c42-24ea9b9920ed.png)


Very strange why it is getting failed from the gulp tasks.

**Comment by wictorwilen** [comment]
Ok, thanks! Let's see if this works then. Run ngrok but with port 3007 (`ngrok http 3007`) - that's the port used by the local server when running any of the `serve` gulp tasks. You might need to open that port on the VM? Or change the port to 80 (`PORT=80` in the `.env` file)

**Comment by arjunumenon** [comment]
Actually I should have put it in the same message. My bad.. ☹️

I had tried that as well, running ngrok with port 3007. It works too.

After that when I manually run gulp serve from the project folder and run ngrok explicitly, I am able to access the tab from using the ngrok URL without any issue.

Issue I saw was only when I runn gulp ngrok-serve.

**Comment by wictorwilen** [comment]
That IS weird..

Looking back at the error message:

```
 url: 'http://127.0.0.1:4040/api/tunnels',
    method: null,
    statusCode: 503,
    statusMessage: 'Service Unavailable',
```

If you manually start ngrok on port 3007 and then navigate to the url above, what do you see?

**Comment by arjunumenon** [comment]
Hi Wictor, Had followed the below steps

1. Started ngrok for port 3007
2. Staarted gulp serve for tabs generated file
3. Tried accessing the ngrok URL and confirmed able to access Tabs
4. Accessed http://127.0.0.1:4040/api/tunnels and i am getting the below response.
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<tunnelListResource>
<Tunnels>
<Name>command_line</Name>
<URI>/api/tunnels/command_line</URI>
<PublicURL>https://87f48433d5f6.ngrok.io</PublicURL>
<Proto>https</Proto>
<Config>
<Addr>http://localhost:3007</Addr>
<Inspect>true</Inspect>
</Config>
<Metrics>
<Conns>
<Count>3</Count>
<Gauge>0</Gauge>
<Rate1>0.03761437082524573</Rate1>
<Rate5>0.009436069711189491</Rate5>
<Rate15>0.0032692495157904534</Rate15>
<P50>5.4348774e+09</P50>
<P90>5.8810457e+09</P90>
<P95>5.8810457e+09</P95>
<P99>5.8810457e+09</P99>
</Conns>
<HTTP>
<Count>6</Count>
<Rate1>0.06546323343926715</Rate1>
<Rate5>0.018354878096858856</Rate5>
<Rate15>0.006478226133726051</Rate15>
<P50>2.6207e+06</P50>
<P90>4.230394e+08</P90>
<P95>4.230394e+08</P95>
<P99>4.230394e+08</P99>
</HTTP>
</Metrics>
</Tunnels>
<Tunnels>
<Name>command_line (http)</Name>
<URI>/api/tunnels/command_line%20%28http%29</URI>
<PublicURL>http://87f48433d5f6.ngrok.io</PublicURL>
<Proto>http</Proto>
<Config>
<Addr>http://localhost:3007</Addr>
<Inspect>true</Inspect>
</Config>
<Metrics>
<Conns>
<Count>0</Count>
<Gauge>0</Gauge>
<Rate1>0</Rate1>
<Rate5>0</Rate5>
<Rate15>0</Rate15>
<P50>0</P50>
<P90>0</P90>
<P95>0</P95>
<P99>0</P99>
</Conns>
<HTTP>
<Count>0</Count>
<Rate1>0</Rate1>
<Rate5>0</Rate5>
<Rate15>0</Rate15>
<P50>0</P50>
<P90>0</P90>
<P95>0</P95>
<P99>0</P99>
</HTTP>
</Metrics>
</Tunnels>
<URI>/api/tunnels</URI>
</tunnelListResource>
```

**Comment by wictorwilen** [comment]
I'm running out of options here, and I've not been able to reproduce this.

To sum it up, here's what I think is going on by looking at the stack trace above and the source code of the ngrok npm package.

1. You run `gulp ngrok-serve`
2. The Ngrok app starts
3. When it's trying to start the tunnel and return the public url, it sends a `POST` message to `api/tunnels` with the options for ngrok (The options is created by the NGROK variables in the `.env` file, and that looks ok by the error message above - `'{"subdomain":"","region":"","addr":"3007","authtoken":"","proto":"http","name":"5cffca7b-bd7d-4613-8a63-250338358a62"}'`)
4.  That POST request returns a 503

Same/similar error has been reported in the ngrok repo: https://github.com/bubenshchykov/ngrok/issues/222.

What if you try to install version 3.4.1 of ngrok (`npm install ngrok@3.4.1 --save-dev`)

**Comment by wictorwilen** [comment]
Also, I just published a preview of the ngrok gulp task to show the correct error message. Please try and add that with: `npm install yoteams-build-core@preview --save-dev`

**Comment by arjunumenon** [comment]
Wow!! That is super quick release wictor 🚀. You are amazing to have a beta release pushed across in a short time. 👏.

Could not check that out today. Will try that out and will let you know how did that go.

**Comment by arjunumenon** [comment]
Hello Wictor - Had tried executing the following commands.
```
npm install ngrok@3.4.1 --save-dev
npm install yoteams-build-core@preview --save-dev
```

After that, when we run `gulp ngrok-serve`, I am still not getting the detailed error. Following is what I am getting.
```

❯ gulp ngrok-serve
[12:38:14] Found additional Yo Teams plugin: yoteams-deploy
[12:38:14] Using gulpfile C:\Arjun\Codes\test-tabs-gen\tabs-1.9\gulpfile.js
[12:38:14] Starting 'ngrok-serve'...
[12:38:14] Starting 'start-ngrok'...
[12:38:14] [NGROK] starting ngrok...
(node:9172) UnhandledPromiseRejectionWarning: Error: Missing error message
    at new PluginError (C:\Arjun\Codes\test-tabs-gen\tabs-1.9\node_modules\plugin-error\index.js:64:11)
    at C:\Arjun\Codes\test-tabs-gen\tabs-1.9\node_modules\yoteams-build-core\dist\ngrokTasks.js:34:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I see that the changes which you had made in the preview is available when I check ngroktasks.js. 

![image](https://user-images.githubusercontent.com/10369964/121647030-91dbf400-cab3-11eb-8bf8-2d4bb479528f.png)


As a next step, since it is specific to my environment, i guess you can go ahead and close / hold the issue so that it will not be gleaming in your backlogs. Let me know if you need any kind of help or support from my end. More than happy to help for community.

Thanks for all the awesome work Wictor.

**Comment by wictorwilen** [comment]
Thanks, this just means that there is no detailed message being thrown by the ngrok connect method :-(. I'd suggest you meanwhile run ngrok separately and let's keep an eye on the issue in the ngrok repo for updates.

**Comment by rabwill** [comment]
I ran into the same issue today @arjunumenon , thanks for reporting and thanks Wictor for the quick response and fix 🎉
windows 10 , Node 14.1.0 
I had to manually set up ngrok and did a gulp serve (after editing the .env) for tabs to work for my little demo. It's def not a blocker but I loved ngrok-serve a lot 😀

**Comment by wictorwilen** [comment]
resolved in yoteams-build-core@1.2.1
